def caesar_cipher(text, key1, key2, mode):
    if key1 < 1 or key1 > 25:
        print("Key 1 must be between 1 and 25.")
        return ""

    if len(key2) < 7 or not key2.isalpha():
        print("Key 2 must contain only Latin alphabet letters and have a length of at least 7 characters.")
        return ""

    # English alphabet
    alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

    # Remove spaces and convert the text to uppercase
    text = text.replace(" ", "").upper()

    # Create a new alphabet by combining key2 and the remaining letters from the original alphabet
    new_alphabet = key2.upper() + "".join(sorted(set(alphabet) - set(key2.upper())))

    # Remove repeated characters from the new alphabet
    new_alphabet = "".join(sorted(set(new_alphabet), key=new_alphabet.index))

    result = ""
    for char in text:
        if 'A' <= char <= 'Z':
            if mode == 'encryption':
                index1 = (alphabet.index(char) + key1) % 26
                index2 = (new_alphabet.index(char)) % 26
                encrypted_char = new_alphabet[(index1 + index2) % 26]
                result += encrypted_char
            else:
                index1 = (new_alphabet.index(char) - key1) % 26
                index2 = (alphabet.index(new_alphabet[index1])) % 26
                decrypted_char = alphabet[index2]
                result += decrypted_char
        else:
            print(f"Character '{char}' is invalid. Only letters A-Z are allowed.")
            return ""

    print("New alphabet generated by Key 2:", new_alphabet)
    return result

# User input
mode = input("Enter the mode (encryption/decryption): ").lower()
key1 = int(input("Enter the first key (1-25): "))
key2 = input("Enter the second key (at least 7 Latin letters): ")
message = input("Enter the message or ciphertext: ")

# Perform encryption or decryption based on the selected mode
#small change
if mode == 'encryption':
    result = caesar_cipher(message, key1, key2, 'encryption')
    print("Encrypted message:", result)
elif mode == 'decryption':
    result = caesar_cipher(message, key1, key2, 'decryption')
    print("Decrypted message:", result)
else:
    print("Invalid mode. Please enter 'encryption' or 'decryption'.")
